name: Snyk Security Vulnerability Scan

on:
  workflow_dispatch:
  pull_request:
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - 'main'

jobs:
  job1:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo --------triggered--------
